name: Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Create Draft Release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: npm install

      - name: Release App
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: npm run electron:build --win --publish always

      - name: Build App without Release
        if: github.ref != 'refs/heads/main'
        run: npm run electron:build --win

  build_on_mac:
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Create Draft Release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: npm install

      - name: Release App
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: npm run electron:build --mac --publish always

      - name: Build App without Release
        if: github.ref != 'refs/heads/main'
        run: npm run electron:build --mac

  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Create Draft Release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: npm install

      - name: Release App
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: npm run electron:build --linux --publish always

      - name: Build App without Release
        if: github.ref != 'refs/heads/main'
        run: npm run electron:build --linux